[config]
output_folder = "test/output"
log_folder = "test/logs"
lock_file = "test/lock"
sample_interval = 300000
sample_idle = 1000
use_ntp = true

[export]
export_file = "test/output.webm"
export_framerate = 24

[settings]
backend = "v4l2"
resolution = "1280x720"
framerate = "24"
device = "/dev/video0"
pixel_format = "yuv420p"
